### ISSUE TITLE
Failed to load the html-significant-other package

### ISSUE THREAD

**Issue by elitonluiz1989** [javakat/html-significant-other#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [html-significant-other](https://github.com/javakat/html-significant-other) package, v0.4.1
### Stack Trace

Failed to load the html-significant-other package

```
At Cannot find module 'bracket-matcher/lib/tag-finder'

Error: Cannot find module 'bracket-matcher/lib/tag-finder'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/home/elitonluiz/.atom/packages/html-significant-other/lib/html-significant-other.js:3:17)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/opt/atom/resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app/src/package.js:672:34)
  at /opt/atom/resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/atom/resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:464:30)
  at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:63:47)
  at /opt/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
  4x -6:45.7 core:backspace (atom-text-editor.editor.mini)
  2x -6:43.2 core:confirm (atom-text-editor.editor.mini)
     -6:33.3 core:delete (atom-text-editor.editor.mini)
  3x -6:29.5 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autoclose-html, v0.15.0
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-plus, v2.4.2
color-picker, v1.4.4
csslint, v1.0.3
emmet, v2.3.4
html-id-class-snippets, v1.4.1
html-significant-other, v0.4.1
jshint, v1.3.0
remote-sync, v2.4.0

# Dev
No dev packages
```

**Comment by jakeharris** [comment]
I'll be working on this this weekend. I'll probably come back and ask you questions about it then.

**Comment by LeKangouroo** [comment]
Thank you @javakat :)

**Comment by jakeharris** [comment]
I just pushed a change that I _think_ will fix the issue. Can I have you pull down the update, @elitonluiz1989? If it works for you, I'll close the issue. If not, I'll need more information.

I think the issue is that I am using some packages internal to Atom that haven't been pushed to npm's registry. As such, they are difficult to include. I assumed they would be present on other people's installations; apparently they are not. So I added [travs/atom-package-dependencies](https://github.com/travs/atom-package-dependencies) to the package and referenced the missing Atom package. This should force its installation.

**Comment by elitonluiz1989** [comment]
Ok, I'll try  today.

**Comment by rickydazla** [comment]
I still have this issue

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [html-significant-other](https://github.com/javakat/html-significant-other) package, v0.5.0

### Stack Trace

Failed to load the html-significant-other package

```
At Cannot find module 'bracket-matcher/lib/tag-finder'

Error: Cannot find module 'bracket-matcher/lib/tag-finder'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/Rick/.atom/packages/html-significant-other/lib/html-significant-other.js:4:17)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "term2",
      "autocomplete-plus",
      "git-tab-status"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.8
file-icons, v1.5.1
git-log, v0.3.0
html-significant-other, v0.5.0
language-liquid, v0.2.0
linter, v0.12.0
linter-csslint, v0.0.11
terminal-panel, v1.10.0

# Dev
No dev packages
```

**Comment by amonks** [comment]
I have this issue also.

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [html-significant-other](https://github.com/javakat/html-significant-other) package, v0.5.0

### Stack Trace

Failed to load the html-significant-other package

```
At Cannot find module 'bracket-matcher/lib/tag-finder'

Error: Cannot find module 'bracket-matcher/lib/tag-finder'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/ajm/.atom/packages/html-significant-other/lib/html-significant-other.js:4:17)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at /opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:30)
  at /opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:370:29
  at exit (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.0.3/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -7:16.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -6:04.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  2x -6:00.9.0 core:save (atom-text-editor.editor.is-focused)
     -4:02.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:57.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:29.8.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
     -1:26.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {}
}
```

### Installed Packages

``` coffee
# User
autoclose-html, v0.18.0
html-significant-other, v0.5.0
vim-mode, v0.57.0

# Dev
No dev packages
```

**Comment by ghost** [comment]
This is still an issue
